---
- hosts: localhost
  gather_facts: no
  
  vars: 
    instant: "{{ lookup('pipe','date -u +%Y-%m-%dT%H:%M:%S%z') }}"
    url: 'https://calendar.google.com/calendar/ical/eonjl72kgg8ah9mip9pb23tlck%40group.calendar.google.com/public/basic.ics'

  tasks:
    - name: Show instant
      debug:
        var: instant

    - name: Test with time = "{{ instant }}"
      debug:
        msg: "There's an event now:"
      when: "{{ lookup('ical', url, instant=instant) }}"
      vars:
        instant: "{{ lookup('pipe','date -u +%Y-%m-%dT%H:%M:%S%z') }}"
 
    - name: Test with time = "{{ instant }}"
      debug:
        msg: "There's an event at  {{ lookup('ical', url, instant=instant) }}"
      when: "{{ lookup('ical', url, instant=instant) }}"
      vars:
        instant: "{{ lookup('pipe','date -v+1H -u +%Y-%m-%dT%H:%M:%S%z') }}"

    - name: Test with time = "{{ instant }}"
      debug:
        msg: "There's an event at {{ instant }}"
      when: "{{ lookup('ical', url, instant=instant) }}"
      vars:
        instant: "{{ lookup('pipe','date -v-30M -u +%Y-%m-%dT%H:%M:%S%z') }}"
       
    - name: Test with time = "{{ instant }} - Now but no instant passed to filter"
      debug:
        msg: "There's an event now: {{ lookup('ical', url )}}"
      when: "{{ lookup('ical', url) }}"
       
